{
 "title": "World Cup 2026 Monitor",
 "tags": [
  "kubernetes",
  "e-commerce",
  "fifa-2026"
 ],
 "refresh": "15s",
 "panels": [
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "Pod Count (Scaling Live)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"world-cup-monitoring\"})",
     "legendFormat": "Running Pods"
    }
   ]
  },
  {
   "title": "App CPU Usage (Per Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"world-cup-monitoring\", pod=~\"world-cup-app.*\"}[5m]) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HPA Current vs Desired Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_hpa_status_current_replicas{hpa=\"world-cup-hpa\"}",
     "legendFormat": "Current Replicas"
    },
    {
     "expr": "kube_hpa_status_desired_replicas{hpa=\"world-cup-hpa\"}",
     "legendFormat": "Desired Replicas"
    }
   ]
  },
  {
   "title": "⚽ Live World Cup Matches",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "targets": [
    { "expr": "wc_live_matches_count", "legendFormat": "Active Matches" }
   ]
  },
  {
   "title": "🏆 Total Tournament Goals",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "targets": [
    { "expr": "wc_total_goals_count", "legendFormat": "Goals Scored" }
   ]
  },
  {
   "title": "🔥 Live Match Action Intensity Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 16 },
   "targets": [
    { "expr": "wc_live_match_intensity", "legendFormat": "Live Match Activity" }
   ]
  }
 ]
}