apiVersion: v1
kind: Namespace
metadata:
  name: world-cup-monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-cup-app
  namespace: world-cup-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world-cup-app
  template:
    metadata:
      labels:
        app: world-cup-app
    spec:
      containers:
      - name: application
        image: devopsdesign/worldcup-app:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "32Mi"
            cpu: "20m"
          limits:
            memory: "96Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: world-cup-metrics-service
  namespace: world-cup-monitoring
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: world-cup-app
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: world-cup-hpa
  namespace: world-cup-monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: world-cup-app
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80